### PR TITLE
Add player markers

### PR DESCRIPTION
**Pull request by barrett777**
Adds player markers, showing where players are on the map

Unfortunately, I'm not able to retrieve player name from the data file.  There is just a UUID identifier, and all the resources I could find online to look up a username from UUID are for the Java edition of Minecraft.

The way I've implemented it, after rendering your world, you will need to edit /maps/playersData.js and manually enter player's names.  You only have to do it once, though, and then it will be remembered.

Here's info on other data available in the player data, in case anyone else wants to add more: https://gist.github.com/barrett777/d7c02000aace08c536f13fb1d3f1cf3b.  It does have pretty much everything else, inventory, equipment, etc.

I've added a new command line option --playericons which I've set as enabled by default

I also updated OpenLayers to v6, which had one breaking change that I fixed (in tileUrlFunction)

I'm only supporting the Overworld for now.  Maybe I will add support for Nether and The End later

Fixes https://github.com/mjungnickel18/papyruscs/issues/15

### CODE REVIEW

**Comment by barrett777** [comment]
Wait on this please, the player markers aren't lining up where they should. I'll work on it this week.

**Comment by mjungnickel18** [comment]
ok, but sounds very cool! How do you get the player positions? are they live or the last position when the map was copied?

**Comment by barrett777** [comment]
They come from the last position when the map was copied, so it will be hard to make 'live' updates for Realms for example.  I'm going to see if I can figure out how to do that though

I'll add another command line option for just updating player positions though, as it is easy to just update player positions without rendering the map, so for people with local servers, they can have live player positions

**Comment by barrett777** [comment]
Ok I think this PR is good.  There may be more bugs but I can fix them as we find them.

I'll still try to find a way to get 'live' positions from Realms one way or another, but it's looking difficult

**Comment by clarkx86** [comment]
> I'll still try to find a way to get 'live' positions from Realms one way or another, but it's looking difficult

One awesome way to fetch live positions would be with the use Websockets and the `/wsserver` command. I experimented with it and you can indeed fetch individual players positions, but unfortunately the `/wsserver` command *only* works in Singleplayer (and Experimental features on if I'm not mistaken). Even if it would work you would need every client to execute this command upon connecting somehow, so to sum things up that option just won't work at the moment... @hach-que developed a bot which fetches the network packages received by the server and already had a working prototype up and running (I believe there is also an open PR from her in this repo).

All in all, that's all I can help you with at the moment... Difficult task to achieve with Bedrock Edition, but certainly not impossible :D.

**Comment by barrett777** [comment]
Thanks for the info :)

I'm going to look into the new scripting API: https://minecraft.gamepedia.com/Bedrock_Edition_beta_scripting_documentation

At this time I'm thinking a client addon that writes each player's position to the local log file, and then updating PapyrusCs to be able to read from that log file.  You can use these addons on Realms as well.  I assume you can find each player's position via the script

**Comment by hach-que** [comment]
Originally I tried out the WebSocket approach, unfortunately yeah, it doesn't work in a lot of cases, and it required you to run a non-headless version of the game to wire it up (so e.g. you can't just hook it up on a Linux server in the cloud somewhere). So I ended up going with the bot approach.

The downside of the bot approach is you basically have to offline mode enabled (so, no protection from cheaters). And because of this, every time the bot joins you have to `/op` it (because otherwise some cheater could just impersonate the bot's UUID and get operator access). This is kind of OK if the bot stayed online reliably, but I've noticed some cases where the bot just stops working, and I haven't had time to investigate.

On top of this, the way the bot is implemented is... interesting to say the least. It periodically applies 100% invisibility potions to itself, and teleports above players to get live position tracking from them. The Minecraft server will only send you live position information for players that are within a certain radius of you, so the bot iterates through players, teleporting itself nearby to "watch" them. Oh, and on top of this, it has to detect when all players are sleeping, and puts itself to sleep in a makeshift bed hidden under bedrock. Needless to say, it's very very complex and hard to catch all the edge cases.

The blocking issue for replacing it with the scripting API, is that so far I haven't seen a way of getting information from the scripting API to some external system (either by writing to files or HTTP requests). It doesn't seem like there's any way to load native modules on the server, and there's no HTTP/file APIs provided by Minecraft.

You *might* be able to get it working using `console.log` (or whatever the scripting API equivalent is), and then having another service watch the log file (or Minecraft server output) to pick up event data, but I haven't looked at whether this actually works.

**Comment by barrett777** [comment]
Thanks for the info :) I'll dig into that later

The map marker positions aren't lining up again, so I need to iron out some more problems with this again before it is ready to merge :(

**Comment by barrett777** [comment]
Ok so the map markers do have the correct coordinates, there is an issue in the OpenLayers code somewhere, and I'm having trouble tracking it down.  I'd love if anyone else could help with this.

It is the strangest thing.  If I view my html file in any browser locally, all the map markers line up where they should.  I can zoom in and they still stay where they should be.  All is well.

image

If I view my same html file on my hosting provider: https://barrett777.github.io/

The page loads at a different zoom level or something, but the markers are in the same position.  Because of this, the markers are not where they should be.

image

Both pages have the same number of zoom levels, but for some reason the tile sizes are different - they are smaller in the 2nd one.

This issue also affects the coordinates shown on hover.

**Comment by barrett777** [comment]
Ok this actually does work fine as is, I'm just a total goofball.  I was changing the chunksPerDimension parameter, but was not publishing the updated html to my web server - only the map images.

@mjungnickel18 This is ready to review, you can see how it looks here: https://barrett777.github.io/

**Comment by mjungnickel18** [comment]
I will take a look and test it soon!

**Comment by mjungnickel18** [comment]
Sorry, Christmas got in the way 😅

**Pull request merged**
