### PR TITLE
Autosearch for worlds and let user select one

### PR DESCRIPTION
**Pull request by aaronaxvig**
I wanted to simplify running this tool for the users such as myself that just run it occasionally on their local computer.  It was tedious to find the path for the world everytime I wanted to use it.  This can also make it super easy for a first time PapyrusCS user to get started...they can get a basic map by simply running the EXE and answering the prompt.

With these changes, if the --world parameter IS NOT specified it will look in the default Bedrock Edition worlds folder and list the found worlds.  It will render the one that the user specifies.

If the --world parameter IS supplied there is no behavior change.

I also added a Resources file to store some static parts of the folders and file names.

### CODE REVIEW

**Comment by aaronaxvig** [comment]
I realized that this will be crappy on Linux.  Does anyone have the path to the worlds folder on Linux?

**Comment by mjungnickel18** [comment]
Have you tried what happens in Linux?

**Comment by aaronaxvig** [comment]
I have not, and I'm not currently in a position to run desktop Linux within a few hours of effort.  Would you like me to put in some OS detection logic?  The required/optional part of the --world attribute would have to stay optional for all OSes I think, but I could still have it tell the user that they must specify it on Linux/Mac.

Or you could say that this is rejected until it is cross-platform compatible; that would be OK with me.

**Comment by mjungnickel18** [comment]
Make it only applicable for Windows with a OS check, then it should be fine.
Minecraft Bedrock does not run unter Linux so, :-)

**Comment by mjungnickel18** [comment]
I can test it on Ubuntu for U

**Comment by aaronaxvig** [comment]
OK this now has the OS check in it

**Comment by mjungnickel18** [comment]
Hi,
I like the change so far :-). This will easiest the start for so many new people who want to make a map of their world.
Do you want to add some more features to it? I'm thinking of:
Set Output Directory: (Default output\<name of the map> 
(You'd have to remove special characters for the folder name from the map name, just to be sure)
Which dimension?
Which file format? (png, faster, but bigger, webp, slow, but smaller)

What do you think?

**Comment by mjungnickel18** [comment]
and: 
show the complate path to the map
or even better
open a explorer window to the map?

**Pull request merged**
